package org.motechproject.ghana.national.functional.patient;

import org.junit.runner.RunWith;
import org.motechproject.functional.data.TestPatient;
import org.motechproject.functional.pages.patient.PatientPage;
import org.motechproject.functional.pages.patient.SearchPatientPage;
import org.motechproject.functional.util.DataGenerator;
import org.motechproject.ghana.national.functional.Generator.StaffGenerator;
import org.motechproject.ghana.national.functional.LoggedInUserFunctionalTest;
import org.motechproject.ghana.national.service.IdentifierGenerationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath:/applicationContext-functional-tests.xml"})
public class PatientTest extends LoggedInUserFunctionalTest {
    @Autowired
    private IdentifierGenerationService identifierGenerationService;
    private DataGenerator dataGenerator;
    @Autowired
    StaffGenerator staffGenerator;

    @BeforeMethod
    public void setUp() {
        dataGenerator = new DataGenerator();
    }

    @Test
    public void shouldCreateAPatientWithAutoGeneratedIdAndSearchForHerByName() {
        final String staffId = staffGenerator.createStaff(browser, homePage);
        PatientPage patientPage = browser.toCreatePatient(homePage);

        TestPatient patient = TestPatient.with("First Name" + dataGenerator.randomString(5), staffId)
                .patientType(TestPatient.PATIENT_TYPE.PREGNANT_MOTHER).estimatedDateOfBirth(false);
        patientPage.create(patient);
        SearchPatientPage searchPatientPage = browser.toSearchPatient(patientPage);
        searchPatientPage.searchWithName(patient.firstName());
        searchPatientPage.displaying(patient);

        searchPatientPage.searchWithName("Middle");
        searchPatientPage.displaying(patient);

        searchPatientPage.searchWithName("Las");
        searchPatientPage.displaying(patient);
    }

    @Test
    public void shouldCreateAPatientWithPrePrintedIdAndSearchForHerByMotechId() {
        final String staffId = staffGenerator.createStaff(browser, homePage);
        PatientPage patientPage = browser.toCreatePatient(homePage);

        TestPatient patient = TestPatient.with("First Name" + dataGenerator.randomString(5), staffId).
                registrationMode(TestPatient.PATIENT_REGN_MODE.USE_PREPRINTED_ID).
                patientType(TestPatient.PATIENT_TYPE.CHILD_UNDER_FIVE).estimatedDateOfBirth(false).
                motechId(identifierGenerationService.newPatientId());
        patientPage.create(patient);
        SearchPatientPage searchPatientPage = browser.toSearchPatient(patientPage);
        searchPatientPage.searchWithMotechId(patient.motechId());
        searchPatientPage.displaying(patient);
    }
}
