package org.motechproject.ghana.national.domain.ivr;

import java.util.List;

import static java.util.Arrays.asList;

public enum MobileMidwifeAudioClips {
    CHILD_CARE_WEEK_1_EN(asList("b_wk1a", "b_wk1b", "b_wk1c"), asList("b_wK1a_prompt", "b_wK1b_prompt", "b_wK1c_prompt")),
    CHILD_CARE_WEEK_1_KAS(asList("b_wk1a", "b_wk1b", "b_wk1c"), asList("b_wK1a_prompt", "b_wK1b_prompt", "b_wK1c_prompt")),
    CHILD_CARE_WEEK_1_NAN(asList("b_wk1a", "b_wk1b", "b_wk1c"), asList("b_wK1a_prompt", "b_wK1b_prompt", "b_wK1c_prompt")),
    CHILD_CARE_WEEK_1_FAN(asList("b_wk1"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_2_EN(asList("b_wk2a", "b_wk2b", "b_wk2c"), asList("b_wK2a_prompt", "b_wK2b_prompt", "b_wK2c_prompt")),
    CHILD_CARE_WEEK_2_KAS(asList("b_wk2a", "b_wk2b", "b_wk2c"), asList("b_wK2a_prompt", "b_wK2b_prompt", "b_wK2c_prompt")),
    CHILD_CARE_WEEK_2_NAN(asList("b_wk2a", "b_wk2b", "b_wk2c"), asList("b_wK2a_prompt", "b_wK2b_prompt", "b_wK2c_prompt")),
    CHILD_CARE_WEEK_2_FAN(asList("b_wk2","b_wk2a"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_3_EN(asList("b_wk3a", "b_wk3b", "b_wk3c"), asList("b_wK3a_prompt", "b_wK3b_prompt", "b_wK3c_prompt")),
    CHILD_CARE_WEEK_3_KAS(asList("b_wk3a", "b_wk3b", "b_wk3c"), asList("b_wK3a_prompt", "b_wK3b_prompt", "b_wK3c_prompt")),
    CHILD_CARE_WEEK_3_NAN(asList("b_wk3a", "b_wk3b", "b_wk3c"), asList("b_wK3a_prompt", "b_wK3b_prompt", "b_wK3c_prompt")),
    CHILD_CARE_WEEK_3_FAN(asList("b_wk3", "b_wk3a"), asList("b_repeat_2_1_prompt", "b_repeat_2_2_prompt")),
    CHILD_CARE_WEEK_4_EN(asList("b_wk4a", "b_wk4b", "b_wk4c"), asList("b_wK4a_prompt", "b_wK4b_prompt", "b_wK4c_prompt")),
    CHILD_CARE_WEEK_4_KAS(asList("b_wk4a", "b_wk4b", "b_wk4c"), asList("b_wK4a_prompt", "b_wK4b_prompt", "b_wK4c_prompt")),
    CHILD_CARE_WEEK_4_NAN(asList("b_wk4a", "b_wk4b", "b_wk4c"), asList("b_wK4a_prompt", "b_wK4b_prompt", "b_wK4c_prompt")),
    CHILD_CARE_WEEK_4_FAN(asList("b_wk4", "b_wk4a", "b_wk4b"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_5_EN(asList("b_wk5"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_5_KAS(asList("b_wk5"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_5_NAN(asList("b_wk5"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_5_FAN(asList("b_wk5"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_6_EN(asList("b_wk6"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_6_KAS(asList("b_wk6"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_6_NAN(asList("b_wk6"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_6_FAN(asList("b_wk6"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_7_EN(asList("b_wk7"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_7_KAS(asList("b_wk7"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_7_NAN(asList("b_wk7"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_7_FAN(asList("b_wk7"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_8_EN(asList("b_wk8"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_8_KAS(asList("b_wk8"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_8_NAN(asList("b_wk8"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_8_FAN(asList("b_wk8"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_9_EN(asList("b_wk9"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_9_KAS(asList("b_wk9"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_9_NAN(asList("b_wk9"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_9_FAN(asList("b_wk9"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_10_EN(asList("b_wk10"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_10_KAS(asList("b_wk10"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_10_NAN(asList("b_wk10"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_10_FAN(asList("b_wk10"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_11_EN(asList("b_wk11"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_11_KAS(asList("b_wk11"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_11_NAN(asList("b_wk11"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_11_FAN(asList("b_wk11"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_12_EN(asList("b_wk12"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_12_KAS(asList("b_wk12"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_12_NAN(asList("b_wk12"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_12_FAN(asList("b_wk12"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_13_EN(asList("b_wk13"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_13_KAS(asList("b_wk13"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_13_NAN(asList("b_wk13"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_13_FAN(asList("b_wk13"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_14_EN(asList("b_wk14"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_14_KAS(asList("b_wk14"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_14_NAN(asList("b_wk14"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_14_FAN(asList("b_wk14"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_15_EN(asList("b_wk15"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_15_KAS(asList("b_wk15"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_15_NAN(asList("b_wk15"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_15_FAN(asList("b_wk15"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_16_EN(asList("b_wk16"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_16_KAS(asList("b_wk16"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_16_NAN(asList("b_wk16"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_16_FAN(asList("b_wk16"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_17_EN(asList("b_wk17"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_17_KAS(asList("b_wk17"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_17_NAN(asList("b_wk17"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_17_FAN(asList("b_wk17"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_18_EN(asList("b_wk18"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_18_KAS(asList("b_wk18"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_18_NAN(asList("b_wk18"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_18_FAN(asList("b_wk18"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_19_EN(asList("b_wk19"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_19_KAS(asList("b_wk19"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_19_NAN(asList("b_wk19"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_19_FAN(asList("b_wk19"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_20_EN(asList("b_wk20"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_20_KAS(asList("b_wk20"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_20_NAN(asList("b_wk20"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_20_FAN(asList("b_wk20"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_21_EN(asList("b_wk21"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_21_KAS(asList("b_wk21"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_21_NAN(asList("b_wk21"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_21_FAN(asList("b_wk21"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_22_EN(asList("b_wk22"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_22_KAS(asList("b_wk22"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_22_NAN(asList("b_wk22"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_22_FAN(asList("b_wk22"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_23_EN(asList("b_wk23"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_23_KAS(asList("b_wk23"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_23_NAN(asList("b_wk23"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_23_FAN(asList("b_wk23"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_24_EN(asList("b_wk24"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_24_KAS(asList("b_wk24"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_24_NAN(asList("b_wk24"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_24_FAN(asList("b_wk24"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_25_EN(asList("b_wk25"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_25_KAS(asList("b_wk25"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_25_NAN(asList("b_wk25"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_25_FAN(asList("b_wk25"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_26_EN(asList("b_wk26"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_26_KAS(asList("b_wk26"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_26_NAN(asList("b_wk26"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_26_FAN(asList("b_wk26"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_27_EN (asList("b_wk27"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_27_KAS(asList("b_wk27"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_27_NAN(asList("b_wk27"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_27_FAN(asList("b_wk27"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_28_EN (asList("b_wk28"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_28_KAS(asList("b_wk28"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_28_NAN(asList("b_wk28"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_28_FAN(asList("b_wk28"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_29_EN (asList("b_wk29"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_29_KAS(asList("b_wk29"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_29_NAN(asList("b_wk29"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_29_FAN(asList("b_wk29"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_30_EN (asList("b_wk30"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_30_KAS(asList("b_wk30"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_30_NAN(asList("b_wk30"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_30_FAN(asList("b_wk30"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_31_EN (asList("b_wk31"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_31_KAS(asList("b_wk31"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_31_NAN(asList("b_wk31"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_31_FAN(asList("b_wk31"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_32_EN (asList("b_wk32"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_32_KAS(asList("b_wk32"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_32_NAN(asList("b_wk32"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_32_FAN(asList("b_wk32"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_33_EN (asList("b_wk33"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_33_KAS(asList("b_wk33"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_33_NAN(asList("b_wk33"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_33_FAN(asList("b_wk33"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_34_EN (asList("b_wk34"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_34_KAS(asList("b_wk34"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_34_NAN(asList("b_wk34"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_34_FAN(asList("b_wk34"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_35_EN (asList("b_wk35"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_35_KAS(asList("b_wk35"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_35_NAN(asList("b_wk35"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_35_FAN(asList("b_wk35"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_36_EN (asList("b_wk36"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_36_KAS(asList("b_wk36"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_36_NAN(asList("b_wk36"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_36_FAN(asList("b_wk36"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_37_EN (asList("b_wk37"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_37_KAS(asList("b_wk37"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_37_NAN(asList("b_wk37"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_37_FAN(asList("b_wk37"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_38_EN (asList("b_wk38"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_38_KAS(asList("b_wk38"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_38_NAN(asList("b_wk38"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_38_FAN(asList("b_wk38"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_39_EN (asList("b_wk39"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_39_KAS(asList("b_wk39"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_39_NAN(asList("b_wk39"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_39_FAN(asList("b_wk39"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_40_EN (asList("b_wk40"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_40_KAS(asList("b_wk40"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_40_NAN(asList("b_wk40"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_40_FAN(asList("b_wk40"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_41_EN (asList("b_wk41"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_41_KAS(asList("b_wk41"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_41_NAN(asList("b_wk41"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_41_FAN(asList("b_wk41"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_42_EN (asList("b_wk42"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_42_KAS(asList("b_wk42"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_42_NAN(asList("b_wk42"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_42_FAN(asList("b_wk42"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_43_EN (asList("b_wk43"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_43_KAS(asList("b_wk43"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_43_NAN(asList("b_wk43"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_43_FAN(asList("b_wk43"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_44_EN (asList("b_wk44"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_44_KAS(asList("b_wk44"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_44_NAN(asList("b_wk44"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_44_FAN(asList("b_wk44"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_45_EN (asList("b_wk45"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_45_KAS(asList("b_wk45"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_45_NAN(asList("b_wk45"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_45_FAN(asList("b_wk45"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_46_EN (asList("b_wk46"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_46_KAS(asList("b_wk46"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_46_NAN(asList("b_wk46"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_46_FAN(asList("b_wk46"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_47_EN (asList("b_wk47"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_47_KAS(asList("b_wk47"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_47_NAN(asList("b_wk47"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_47_FAN(asList("b_wk47"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_48_EN (asList("b_wk48"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_48_KAS(asList("b_wk48"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_48_NAN(asList("b_wk48"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_48_FAN(asList("b_wk48"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_49_EN (asList("b_wk49"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_49_KAS(asList("b_wk49"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_49_NAN(asList("b_wk49"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_49_FAN(asList("b_wk49"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_50_EN (asList("b_wk50"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_50_KAS(asList("b_wk50"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_50_NAN(asList("b_wk50"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_50_FAN(asList("b_wk50"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_51_EN (asList("b_wk51"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_51_KAS(asList("b_wk51"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_51_NAN(asList("b_wk51"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_51_FAN(asList("b_wk51"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_52_EN (asList("b_wk52"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_52_KAS(asList("b_wk52"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_52_NAN(asList("b_wk52"), asList("b_repeat_prompt")),
    CHILD_CARE_WEEK_52_FAN(asList("b_wk52"), asList("b_repeat_prompt")),
    PREGNANCY_WEEK_5_EN (asList("p_wk5a", "p_wk5b", "p_wk5c"), asList("p_wK5a_prompt", "p_wK5b_prompt", "p_wK5c_prompt")),
    PREGNANCY_WEEK_5_KAS(asList("p_wk5a", "p_wk5b", "p_wk5c"), asList("p_wK5a_prompt", "p_wK5b_prompt", "p_wK5c_prompt")),
    PREGNANCY_WEEK_5_NAN(asList("p_wk5a", "p_wk5b", "p_wk5c"), asList("p_wK5a_prompt", "p_wK5b_prompt", "p_wK5c_prompt")),
    PREGNANCY_WEEK_5_FAN(asList("p_wk5a", "p_wk5b", "p_wk5c"), asList("p_wK5a_prompt", "p_wK5b_prompt", "p_wK5c_prompt")),
    PREGNANCY_WEEK_6_EN (asList("p_wk6a", "p_wk6b", "p_wk6c"), asList("p_wK6a_prompt", "p_wK6b_prompt", "p_wK6c_prompt")),
    PREGNANCY_WEEK_6_KAS(asList("p_wk6a", "p_wk6b", "p_wk6c"), asList("p_wK6a_prompt", "p_wK6b_prompt", "p_wK6c_prompt")),
    PREGNANCY_WEEK_6_NAN(asList("p_wk6a", "p_wk6b", "p_wk6c"), asList("p_wK6a_prompt", "p_wK6b_prompt", "p_wK6c_prompt")),
    PREGNANCY_WEEK_6_FAN(asList("p_wk6a", "p_wk6b", "p_wk6c"), asList("p_wK6a_prompt", "p_wK6b_prompt", "p_wK6c_prompt")),
    PREGNANCY_WEEK_7_EN (asList("p_wk7a", "p_wk7b", "p_wk7c"), asList("p_wK7a_prompt", "p_wK7b_prompt", "p_wK7c_prompt")),
    PREGNANCY_WEEK_7_KAS(asList("p_wk7a", "p_wk7b", "p_wk7c"), asList("p_wK7a_prompt", "p_wK7b_prompt", "p_wK7c_prompt")),
    PREGNANCY_WEEK_7_NAN(asList("p_wk7a", "p_wk7b", "p_wk7c"), asList("p_wK7a_prompt", "p_wK7b_prompt", "p_wK7c_prompt")),
    PREGNANCY_WEEK_7_FAN(asList("p_wk7a", "p_wk7b", "p_wk7c"), asList("p_wK7a_prompt", "p_wK7b_prompt", "p_wK7c_prompt")),
    PREGNANCY_WEEK_8_EN (asList("p_wk8a", "p_wk8b", "p_wk8c"), asList("p_wK8a_prompt", "p_wK8b_prompt", "p_wK8c_prompt")),
    PREGNANCY_WEEK_8_KAS(asList("p_wk8a", "p_wk8b", "p_wk8c"), asList("p_wK8a_prompt", "p_wK8b_prompt", "p_wK8c_prompt")),
    PREGNANCY_WEEK_8_NAN(asList("p_wk8a", "p_wk8b", "p_wk8c"), asList("p_wK8a_prompt", "p_wK8b_prompt", "p_wK8c_prompt")),
    PREGNANCY_WEEK_8_FAN(asList("p_wk8a", "p_wk8b", "p_wk8c"), asList("p_wK8a_prompt", "p_wK8b_prompt", "p_wK8c_prompt")),
    PREGNANCY_WEEK_9_EN (asList("p_wk9a", "p_wk9b", "p_wk9c"), asList("p_wK9a_prompt", "p_wK9b_prompt", "p_wK9c_prompt")),
    PREGNANCY_WEEK_9_KAS(asList("p_wk9a", "p_wk9b", "p_wk9c"), asList("p_wK9a_prompt", "p_wK9b_prompt", "p_wK9c_prompt")),
    PREGNANCY_WEEK_9_NAN(asList("p_wk9a", "p_wk9b", "p_wk9c"), asList("p_wK9a_prompt", "p_wK9b_prompt", "p_wK9c_prompt")),
    PREGNANCY_WEEK_9_FAN(asList("p_wk9a", "p_wk9b", "p_wk9c"), asList("p_wK9a_prompt", "p_wK9b_prompt", "p_wK9c_prompt")),
    PREGNANCY_WEEK_10_EN (asList("p_wk10a", "p_wk10b", "p_wk10c"), asList("p_wK10a_prompt", "p_wK10b_prompt", "p_wK10c_prompt")),
    PREGNANCY_WEEK_10_KAS(asList("p_wk10a", "p_wk10b", "p_wk10c"), asList("p_wK10a_prompt", "p_wK10b_prompt", "p_wK10c_prompt")),
    PREGNANCY_WEEK_10_NAN(asList("p_wk10a", "p_wk10b", "p_wk10c"), asList("p_wK10a_prompt", "p_wK10b_prompt", "p_wK10c_prompt")),
    PREGNANCY_WEEK_10_FAN(asList("p_wk10a", "p_wk10b", "p_wk10c"), asList("p_wK10a_prompt", "p_wK10b_prompt", "p_wK10c_prompt")),
    PREGNANCY_WEEK_11_EN (asList("p_wk11a", "p_wk11b", "p_wk11c"), asList("p_wK11a_prompt", "p_wK11b_prompt", "p_wK11c_prompt")),
    PREGNANCY_WEEK_11_KAS(asList("p_wk11a", "p_wk11b", "p_wk11c"), asList("p_wK11a_prompt", "p_wK11b_prompt", "p_wK11c_prompt")),
    PREGNANCY_WEEK_11_NAN(asList("p_wk11a", "p_wk11b", "p_wk11c"), asList("p_wK11a_prompt", "p_wK11b_prompt", "p_wK11c_prompt")),
    PREGNANCY_WEEK_11_FAN(asList("p_wk11a", "p_wk11b", "p_wk11c"), asList("p_wK11a_prompt", "p_wK11b_prompt", "p_wK11c_prompt")),
    PREGNANCY_WEEK_12_EN (asList("p_wk12a", "p_wk12b", "p_wk12c"), asList("p_wK12a_prompt", "p_wK12b_prompt", "p_wK12c_prompt")),
    PREGNANCY_WEEK_12_KAS(asList("p_wk12a", "p_wk12b", "p_wk12c"), asList("p_wK12a_prompt", "p_wK12b_prompt", "p_wK12c_prompt")),
    PREGNANCY_WEEK_12_NAN(asList("p_wk12a", "p_wk12b", "p_wk12c"), asList("p_wK12a_prompt", "p_wK12b_prompt", "p_wK12c_prompt")),
    PREGNANCY_WEEK_12_FAN(asList("p_wk12a", "p_wk12b", "p_wk12c"), asList("p_wK12a_prompt", "p_wK12b_prompt", "p_wK12c_prompt")),
    PREGNANCY_WEEK_13_EN (asList("p_wk13a", "p_wk13b", "p_wk13c"), asList("p_wK13a_prompt", "p_wK13b_prompt", "p_wK13c_prompt")),
    PREGNANCY_WEEK_13_KAS(asList("p_wk13a", "p_wk13b", "p_wk13c"), asList("p_wK13a_prompt", "p_wK13b_prompt", "p_wK13c_prompt")),
    PREGNANCY_WEEK_13_NAN(asList("p_wk13a", "p_wk13b", "p_wk13c"), asList("p_wK13a_prompt", "p_wK13b_prompt", "p_wK13c_prompt")),
    PREGNANCY_WEEK_13_FAN(asList("p_wk13a", "p_wk13b", "p_wk13c"), asList("p_wK13a_prompt", "p_wK13b_prompt", "p_wK13c_prompt")),
    PREGNANCY_WEEK_14_EN (asList("p_wk14a", "p_wk14b", "p_wk14c"), asList("p_wK14a_prompt", "p_wK14b_prompt", "p_wK14c_prompt")),
    PREGNANCY_WEEK_14_KAS(asList("p_wk14a", "p_wk14b", "p_wk14c"), asList("p_wK14a_prompt", "p_wK14b_prompt", "p_wK14c_prompt")),
    PREGNANCY_WEEK_14_NAN(asList("p_wk14a", "p_wk14b", "p_wk14c"), asList("p_wK14a_prompt", "p_wK14b_prompt", "p_wK14c_prompt")),
    PREGNANCY_WEEK_14_FAN(asList("p_wk14a", "p_wk14b", "p_wk14c"), asList("p_wK14a_prompt", "p_wK14b_prompt", "p_wK14c_prompt")),
    PREGNANCY_WEEK_15_EN (asList("p_wk15a", "p_wk15b", "p_wk15c"), asList("p_wK15a_prompt", "p_wK15b_prompt", "p_wK15c_prompt")),
    PREGNANCY_WEEK_15_KAS(asList("p_wk15a", "p_wk15b", "p_wk15c"), asList("p_wK15a_prompt", "p_wK15b_prompt", "p_wK15c_prompt")),
    PREGNANCY_WEEK_15_NAN(asList("p_wk15a", "p_wk15b", "p_wk15c"), asList("p_wK15a_prompt", "p_wK15b_prompt", "p_wK15c_prompt")),
    PREGNANCY_WEEK_15_FAN(asList("p_wk15a", "p_wk15b", "p_wk15c"), asList("p_wK15a_prompt", "p_wK15b_prompt", "p_wK15c_prompt")),
    PREGNANCY_WEEK_16_EN (asList("p_wk16a", "p_wk16b", "p_wk16c"), asList("p_wK16a_prompt", "p_wK16b_prompt", "p_wK16c_prompt")),
    PREGNANCY_WEEK_16_KAS(asList("p_wk16a", "p_wk16b", "p_wk16c"), asList("p_wK16a_prompt", "p_wK16b_prompt", "p_wK16c_prompt")),
    PREGNANCY_WEEK_16_NAN(asList("p_wk16a", "p_wk16b", "p_wk16c"), asList("p_wK16a_prompt", "p_wK16b_prompt", "p_wK16c_prompt")),
    PREGNANCY_WEEK_16_FAN(asList("p_wk16a", "p_wk16b", "p_wk16c"), asList("p_wK16a_prompt", "p_wK16b_prompt", "p_wK16c_prompt")),
    PREGNANCY_WEEK_17_EN (asList("p_wk17a", "p_wk17b", "p_wk17c"), asList("p_wK17a_prompt", "p_wK17b_prompt", "p_wK17c_prompt")),
    PREGNANCY_WEEK_17_KAS(asList("p_wk17a", "p_wk17b", "p_wk17c"), asList("p_wK17a_prompt", "p_wK17b_prompt", "p_wK17c_prompt")),
    PREGNANCY_WEEK_17_NAN(asList("p_wk17a", "p_wk17b", "p_wk17c"), asList("p_wK17a_prompt", "p_wK17b_prompt", "p_wK17c_prompt")),
    PREGNANCY_WEEK_17_FAN(asList("p_wk17a", "p_wk17b", "p_wk17c"), asList("p_wK17a_prompt", "p_wK17b_prompt", "p_wK17c_prompt")),
    PREGNANCY_WEEK_18_EN (asList("p_wk18a", "p_wk18b", "p_wk18c"), asList("p_wK18a_prompt", "p_wK18b_prompt", "p_wK18c_prompt")),
    PREGNANCY_WEEK_18_KAS(asList("p_wk18a", "p_wk18b", "p_wk18c"), asList("p_wK18a_prompt", "p_wK18b_prompt", "p_wK18c_prompt")),
    PREGNANCY_WEEK_18_NAN(asList("p_wk18a", "p_wk18b", "p_wk18c"), asList("p_wK18a_prompt", "p_wK18b_prompt", "p_wK18c_prompt")),
    PREGNANCY_WEEK_18_FAN(asList("p_wk18a", "p_wk18b", "p_wk18c"), asList("p_wK18a_prompt", "p_wK18b_prompt", "p_wK18c_prompt")),
    PREGNANCY_WEEK_19_EN (asList("p_wk19a", "p_wk19b", "p_wk19c"), asList("p_wK19a_prompt", "p_wK19b_prompt", "p_wK19c_prompt")),
    PREGNANCY_WEEK_19_KAS(asList("p_wk19a", "p_wk19b", "p_wk19c"), asList("p_wK19a_prompt", "p_wK19b_prompt", "p_wK19c_prompt")),
    PREGNANCY_WEEK_19_NAN(asList("p_wk19a", "p_wk19b", "p_wk19c"), asList("p_wK19a_prompt", "p_wK19b_prompt", "p_wK19c_prompt")),
    PREGNANCY_WEEK_19_FAN(asList("p_wk19a", "p_wk19b", "p_wk19c"), asList("p_wK19a_prompt", "p_wK19b_prompt", "p_wK19c_prompt")),
    PREGNANCY_WEEK_20_EN (asList("p_wk20a", "p_wk20b", "p_wk20c"), asList("p_wK20a_prompt", "p_wK20b_prompt", "p_wK20c_prompt")),
    PREGNANCY_WEEK_20_KAS(asList("p_wk20a", "p_wk20b", "p_wk20c"), asList("p_wK20a_prompt", "p_wK20b_prompt", "p_wK20c_prompt")),
    PREGNANCY_WEEK_20_NAN(asList("p_wk20a", "p_wk20b", "p_wk20c"), asList("p_wK20a_prompt", "p_wK20b_prompt", "p_wK20c_prompt")),
    PREGNANCY_WEEK_20_FAN(asList("p_wk20a", "p_wk20b", "p_wk20c"), asList("p_wK20a_prompt", "p_wK20b_prompt", "p_wK20c_prompt")),
    PREGNANCY_WEEK_21_EN (asList("p_wk21a", "p_wk21b", "p_wk21c"), asList("p_wK21a_prompt", "p_wK21b_prompt", "p_wK21c_prompt")),
    PREGNANCY_WEEK_21_KAS(asList("p_wk21a", "p_wk21b", "p_wk21c"), asList("p_wK21a_prompt", "p_wK21b_prompt", "p_wK21c_prompt")),
    PREGNANCY_WEEK_21_NAN(asList("p_wk21a", "p_wk21b", "p_wk21c"), asList("p_wK21a_prompt", "p_wK21b_prompt", "p_wK21c_prompt")),
    PREGNANCY_WEEK_21_FAN(asList("p_wk21a", "p_wk21b", "p_wk21c"), asList("p_wK21a_prompt", "p_wK21b_prompt", "p_wK21c_prompt")),
    PREGNANCY_WEEK_22_EN (asList("p_wk22a", "p_wk22b", "p_wk22c"), asList("p_wK22a_prompt", "p_wK22b_prompt", "p_wK22c_prompt")),
    PREGNANCY_WEEK_22_KAS(asList("p_wk22a", "p_wk22b", "p_wk22c"), asList("p_wK22a_prompt", "p_wK22b_prompt", "p_wK22c_prompt")),
    PREGNANCY_WEEK_22_NAN(asList("p_wk22a", "p_wk22b", "p_wk22c"), asList("p_wK22a_prompt", "p_wK22b_prompt", "p_wK22c_prompt")),
    PREGNANCY_WEEK_22_FAN(asList("p_wk22a", "p_wk22b", "p_wk22c"), asList("p_wK22a_prompt", "p_wK22b_prompt", "p_wK22c_prompt")),
    PREGNANCY_WEEK_23_EN (asList("p_wk23a", "p_wk23b", "p_wk23c"), asList("p_wK23a_prompt", "p_wK23b_prompt", "p_wK23c_prompt")),
    PREGNANCY_WEEK_23_KAS(asList("p_wk23a", "p_wk23b", "p_wk23c"), asList("p_wK23a_prompt", "p_wK23b_prompt", "p_wK23c_prompt")),
    PREGNANCY_WEEK_23_NAN(asList("p_wk23a", "p_wk23b", "p_wk23c"), asList("p_wK23a_prompt", "p_wK23b_prompt", "p_wK23c_prompt")),
    PREGNANCY_WEEK_23_FAN(asList("p_wk23a", "p_wk23b", "p_wk23c"), asList("p_wK23a_prompt", "p_wK23b_prompt", "p_wK23c_prompt")),
    PREGNANCY_WEEK_24_EN (asList("p_wk24a", "p_wk24b", "p_wk24c"), asList("p_wK24a_prompt", "p_wK24b_prompt", "p_wK24c_prompt")),
    PREGNANCY_WEEK_24_KAS(asList("p_wk24a", "p_wk24b", "p_wk24c"), asList("p_wK24a_prompt", "p_wK24b_prompt", "p_wK24c_prompt")),
    PREGNANCY_WEEK_24_NAN(asList("p_wk24a", "p_wk24b", "p_wk24c"), asList("p_wK24a_prompt", "p_wK24b_prompt", "p_wK24c_prompt")),
    PREGNANCY_WEEK_24_FAN(asList("p_wk24a", "p_wk24b", "p_wk24c"), asList("p_wK24a_prompt", "p_wK24b_prompt", "p_wK24c_prompt")),
    PREGNANCY_WEEK_25_EN (asList("p_wk25a", "p_wk25b", "p_wk25c"), asList("p_wK25a_prompt", "p_wK25b_prompt", "p_wK25c_prompt")),
    PREGNANCY_WEEK_25_KAS(asList("p_wk25a", "p_wk25b", "p_wk25c"), asList("p_wK25a_prompt", "p_wK25b_prompt", "p_wK25c_prompt")),
    PREGNANCY_WEEK_25_NAN(asList("p_wk25a", "p_wk25b", "p_wk25c"), asList("p_wK25a_prompt", "p_wK25b_prompt", "p_wK25c_prompt")),
    PREGNANCY_WEEK_25_FAN(asList("p_wk25a", "p_wk25b", "p_wk25c"), asList("p_wK25a_prompt", "p_wK25b_prompt", "p_wK25c_prompt")),
    PREGNANCY_WEEK_26_EN (asList("p_wk26a", "p_wk26b", "p_wk26c"), asList("p_wK26a_prompt", "p_wK26b_prompt", "p_wK26c_prompt")),
    PREGNANCY_WEEK_26_KAS(asList("p_wk26a", "p_wk26b", "p_wk26c"), asList("p_wK26a_prompt", "p_wK26b_prompt", "p_wK26c_prompt")),
    PREGNANCY_WEEK_26_NAN(asList("p_wk26a", "p_wk26b", "p_wk26c"), asList("p_wK26a_prompt", "p_wK26b_prompt", "p_wK26c_prompt")),
    PREGNANCY_WEEK_26_FAN(asList("p_wk26a", "p_wk26b", "p_wk26c"), asList("p_wK26a_prompt", "p_wK26b_prompt", "p_wK26c_prompt")),
    PREGNANCY_WEEK_27_EN (asList("p_wk27a", "p_wk27b", "p_wk27c"), asList("p_wK27a_prompt", "p_wK27b_prompt", "p_wK27c_prompt")),
    PREGNANCY_WEEK_27_KAS(asList("p_wk27a", "p_wk27b", "p_wk27c"), asList("p_wK27a_prompt", "p_wK27b_prompt", "p_wK27c_prompt")),
    PREGNANCY_WEEK_27_NAN(asList("p_wk27a", "p_wk27b", "p_wk27c"), asList("p_wK27a_prompt", "p_wK27b_prompt", "p_wK27c_prompt")),
    PREGNANCY_WEEK_27_FAN(asList("p_wk27a", "p_wk27b", "p_wk27c"), asList("p_wK27a_prompt", "p_wK27b_prompt", "p_wK27c_prompt")),
    PREGNANCY_WEEK_28_EN (asList("p_wk28a", "p_wk28b", "p_wk28c"), asList("p_wK28a_prompt", "p_wK28b_prompt", "p_wK28c_prompt")),
    PREGNANCY_WEEK_28_KAS(asList("p_wk28a", "p_wk28b", "p_wk28c"), asList("p_wK28a_prompt", "p_wK28b_prompt", "p_wK28c_prompt")),
    PREGNANCY_WEEK_28_NAN(asList("p_wk28a", "p_wk28b", "p_wk28c"), asList("p_wK28a_prompt", "p_wK28b_prompt", "p_wK28c_prompt")),
    PREGNANCY_WEEK_28_FAN(asList("p_wk28a", "p_wk28b", "p_wk28c"), asList("p_wK28a_prompt", "p_wK28b_prompt", "p_wK28c_prompt")),
    PREGNANCY_WEEK_29_EN (asList("p_wk29a", "p_wk29b", "p_wk29c"), asList("p_wK29a_prompt", "p_wK29b_prompt", "p_wK29c_prompt")),
    PREGNANCY_WEEK_29_KAS(asList("p_wk29a", "p_wk29b", "p_wk29c"), asList("p_wK29a_prompt", "p_wK29b_prompt", "p_wK29c_prompt")),
    PREGNANCY_WEEK_29_NAN(asList("p_wk29a", "p_wk29b", "p_wk29c"), asList("p_wK29a_prompt", "p_wK29b_prompt", "p_wK29c_prompt")),
    PREGNANCY_WEEK_29_FAN(asList("p_wk29a", "p_wk29b", "p_wk29c"), asList("p_wK29a_prompt", "p_wK29b_prompt", "p_wK29c_prompt")),
    PREGNANCY_WEEK_30_EN (asList("p_wk30a", "p_wk30b", "p_wk30c"), asList("p_wK30a_prompt", "p_wK30b_prompt", "p_wK30c_prompt")),
    PREGNANCY_WEEK_30_KAS(asList("p_wk30a", "p_wk30b", "p_wk30c"), asList("p_wK30a_prompt", "p_wK30b_prompt", "p_wK30c_prompt")),
    PREGNANCY_WEEK_30_NAN(asList("p_wk30a", "p_wk30b", "p_wk30c"), asList("p_wK30a_prompt", "p_wK30b_prompt", "p_wK30c_prompt")),
    PREGNANCY_WEEK_30_FAN(asList("p_wk30a", "p_wk30b", "p_wk30c"), asList("p_wK30a_prompt", "p_wK30b_prompt", "p_wK30c_prompt")),
    PREGNANCY_WEEK_31_EN (asList("p_wk31a", "p_wk31b", "p_wk31c"), asList("p_wK31a_prompt", "p_wK31b_prompt", "p_wK31c_prompt")),
    PREGNANCY_WEEK_31_KAS(asList("p_wk31a", "p_wk31b", "p_wk31c"), asList("p_wK31a_prompt", "p_wK31b_prompt", "p_wK31c_prompt")),
    PREGNANCY_WEEK_31_NAN(asList("p_wk31a", "p_wk31b", "p_wk31c"), asList("p_wK31a_prompt", "p_wK31b_prompt", "p_wK31c_prompt")),
    PREGNANCY_WEEK_31_FAN(asList("p_wk31a", "p_wk31b", "p_wk31c"), asList("p_wK31a_prompt", "p_wK31b_prompt", "p_wK31c_prompt")),
    PREGNANCY_WEEK_32_EN (asList("p_wk32a", "p_wk32b", "p_wk32c"), asList("p_wK32a_prompt", "p_wK32b_prompt", "p_wK32c_prompt")),
    PREGNANCY_WEEK_32_KAS(asList("p_wk32a", "p_wk32b", "p_wk32c"), asList("p_wK32a_prompt", "p_wK32b_prompt", "p_wK32c_prompt")),
    PREGNANCY_WEEK_32_NAN(asList("p_wk32a", "p_wk32b", "p_wk32c"), asList("p_wK32a_prompt", "p_wK32b_prompt", "p_wK32c_prompt")),
    PREGNANCY_WEEK_32_FAN(asList("p_wk32a", "p_wk32b", "p_wk32c"), asList("p_wK32a_prompt", "p_wK32b_prompt", "p_wK32c_prompt")),
    PREGNANCY_WEEK_33_EN (asList("p_wk33a", "p_wk33b", "p_wk33c"), asList("p_wK33a_prompt", "p_wK33b_prompt", "p_wK33c_prompt")),
    PREGNANCY_WEEK_33_KAS(asList("p_wk33a", "p_wk33b", "p_wk33c"), asList("p_wK33a_prompt", "p_wK33b_prompt", "p_wK33c_prompt")),
    PREGNANCY_WEEK_33_NAN(asList("p_wk33a", "p_wk33b", "p_wk33c"), asList("p_wK33a_prompt", "p_wK33b_prompt", "p_wK33c_prompt")),
    PREGNANCY_WEEK_33_FAN(asList("p_wk33a", "p_wk33b", "p_wk33c"), asList("p_wK33a_prompt", "p_wK33b_prompt", "p_wK33c_prompt")),
    PREGNANCY_WEEK_34_EN (asList("p_wk34a", "p_wk34b", "p_wk34c"), asList("p_wK34a_prompt", "p_wK34b_prompt", "p_wK34c_prompt")),
    PREGNANCY_WEEK_34_KAS(asList("p_wk34a", "p_wk34b", "p_wk34c"), asList("p_wK34a_prompt", "p_wK34b_prompt", "p_wK34c_prompt")),
    PREGNANCY_WEEK_34_NAN(asList("p_wk34a", "p_wk34b", "p_wk34c"), asList("p_wK34a_prompt", "p_wK34b_prompt", "p_wK34c_prompt")),
    PREGNANCY_WEEK_34_FAN(asList("p_wk34a", "p_wk34b", "p_wk34c"), asList("p_wK34a_prompt", "p_wK34b_prompt", "p_wK34c_prompt")),
    PREGNANCY_WEEK_35_EN (asList("p_wk35a", "p_wk35b", "p_wk35c"), asList("p_wK35a_prompt", "p_wK35b_prompt", "p_wK35c_prompt")),
    PREGNANCY_WEEK_35_KAS(asList("p_wk35a", "p_wk35b", "p_wk35c"), asList("p_wK35a_prompt", "p_wK35b_prompt", "p_wK35c_prompt")),
    PREGNANCY_WEEK_35_NAN(asList("p_wk35a", "p_wk35b", "p_wk35c"), asList("p_wK35a_prompt", "p_wK35b_prompt", "p_wK35c_prompt")),
    PREGNANCY_WEEK_35_FAN(asList("p_wk35a", "p_wk35b", "p_wk35c"), asList("p_wK35a_prompt", "p_wK35b_prompt", "p_wK35c_prompt")),
    PREGNANCY_WEEK_36_EN (asList("p_wk36a", "p_wk36b", "p_wk36c"), asList("p_wK36a_prompt", "p_wK36b_prompt", "p_wK36c_prompt")),
    PREGNANCY_WEEK_36_KAS(asList("p_wk36a", "p_wk36b", "p_wk36c"), asList("p_wK36a_prompt", "p_wK36b_prompt", "p_wK36c_prompt")),
    PREGNANCY_WEEK_36_NAN(asList("p_wk36a", "p_wk36b", "p_wk36c"), asList("p_wK36a_prompt", "p_wK36b_prompt", "p_wK36c_prompt")),
    PREGNANCY_WEEK_36_FAN(asList("p_wk36a", "p_wk36b", "p_wk36c"), asList("p_wK36a_prompt", "p_wK36b_prompt", "p_wK36c_prompt")),
    PREGNANCY_WEEK_37_EN (asList("p_wk37a", "p_wk37b", "p_wk37c"), asList("p_wK37a_prompt", "p_wK37b_prompt", "p_wK37c_prompt")),
    PREGNANCY_WEEK_37_KAS(asList("p_wk37a", "p_wk37b", "p_wk37c"), asList("p_wK37a_prompt", "p_wK37b_prompt", "p_wK37c_prompt")),
    PREGNANCY_WEEK_37_NAN(asList("p_wk37a", "p_wk37b", "p_wk37c"), asList("p_wK37a_prompt", "p_wK37b_prompt", "p_wK37c_prompt")),
    PREGNANCY_WEEK_37_FAN(asList("p_wk37a", "p_wk37b", "p_wk37c"), asList("p_wK37a_prompt", "p_wK37b_prompt", "p_wK37c_prompt")),
    PREGNANCY_WEEK_38_EN (asList("p_wk38a", "p_wk38b", "p_wk38c"), asList("p_wK38a_prompt", "p_wK38b_prompt", "p_wK38c_prompt")),
    PREGNANCY_WEEK_38_KAS(asList("p_wk38a", "p_wk38b", "p_wk38c"), asList("p_wK38a_prompt", "p_wK38b_prompt", "p_wK38c_prompt")),
    PREGNANCY_WEEK_38_NAN(asList("p_wk38a", "p_wk38b", "p_wk38c"), asList("p_wK38a_prompt", "p_wK38b_prompt", "p_wK38c_prompt")),
    PREGNANCY_WEEK_38_FAN(asList("p_wk38a", "p_wk38b", "p_wk38c"), asList("p_wK38a_prompt", "p_wK38b_prompt", "p_wK38c_prompt")),
    PREGNANCY_WEEK_39_EN (asList("p_wk39a", "p_wk39b", "p_wk39c"), asList("p_wK39a_prompt", "p_wK39b_prompt", "p_wK39c_prompt")),
    PREGNANCY_WEEK_39_KAS(asList("p_wk39a", "p_wk39b", "p_wk39c"), asList("p_wK39a_prompt", "p_wK39b_prompt", "p_wK39c_prompt")),
    PREGNANCY_WEEK_39_NAN(asList("p_wk39a", "p_wk39b", "p_wk39c"), asList("p_wK39a_prompt", "p_wK39b_prompt", "p_wK39c_prompt")),
    PREGNANCY_WEEK_39_FAN(asList("p_wk39a", "p_wk39b", "p_wk39c"), asList("p_wK39a_prompt", "p_wK39b_prompt", "p_wK39c_prompt")),
    PREGNANCY_WEEK_40_EN (asList("p_wk40a", "p_wk40b", "p_wk40c"), asList("p_wK40a_prompt", "p_wK40b_prompt", "p_wK40c_prompt")),
    PREGNANCY_WEEK_40_KAS(asList("p_wk40a", "p_wk40b", "p_wk40c"), asList("p_wK40a_prompt", "p_wK40b_prompt", "p_wK40c_prompt")),
    PREGNANCY_WEEK_40_NAN(asList("p_wk40a", "p_wk40b", "p_wk40c"), asList("p_wK40a_prompt", "p_wK40b_prompt", "p_wK40c_prompt")),
    PREGNANCY_WEEK_40_FAN(asList("p_wk40a", "p_wk40b", "p_wk40c"), asList("p_wK40a_prompt", "p_wK40b_prompt", "p_wK40c_prompt"));




    private final List<String> clipNames;
    private final List<String> promptClipNames;

    MobileMidwifeAudioClips(List<String> clipNames, List<String> promptClipNames) {
        this.clipNames = clipNames;
        this.promptClipNames = promptClipNames;
    }

    public List<String> getClipNames() {
        return clipNames;
    }

    public List<String> getPromptClipNames() {
        return promptClipNames;
    }

    public static MobileMidwifeAudioClips instance(String programName, String week, String language){
        return MobileMidwifeAudioClips.valueOf(programName.toUpperCase() + "_WEEK_" + week + "_" +language.toUpperCase());
    }
}




