package org.motechproject.ghana.national.domain;

public class SmsTemplateKeys {
    public static final String PREGNANCY_ALERT_SMS_KEY = "PREGNANCY_ALERT_SMS_KEY";
    public static final String TT_VACCINATION_SMS_KEY = "TT_VACCINATION_SMS_KEY";
    public static final String ANC_IPTp_VACCINATION_SMS_KEY = "ANC_IPTp_VACCINATION_SMS_KEY";
    public static final String BCG_SMS_KEY = "BCG_SMS_KEY";
    public static final String ANC_VISIT_SMS_KEY = "ANC_VISIT_SMS_KEY";
    public static final String REGISTER_SUCCESS_SMS_KEY = "REGISTER_SUCCESS_SMS_KEY";
    public static final String CWC_MEASLES_SMS_KEY = "CWC_MEASLES_SMS_KEY";
    public static final String CWC_PENTA_SMS_KEY = "CWC_PENTA_SMS_KEY";
    public static final String CWC_YF_SMS_KEY = "CWC_YF_SMS_KEY";
    public static final String CWC_OPV_SMS_KEY = "CWC_OPV_SMS_KEY";
    public static final String CWC_IPTi_VACCINATION_SMS_KEY = "CWC_IPTi_VACCINATION_SMS_KEY";
    public static final String PNC_MOTHER_SMS_KEY = "PNC_MOTHER_SMS_KEY";
    public static final String PNC_CHILD_SMS_KEY = "PNC_CHILD_SMS_KEY";
    public static final String FACILITIES_DEFAULT_MESSAGE_KEY = "FACILITIES_DEFAULT_MESSAGE_KEY";
    public static final String PATIENT_ANC_VISIT_DUE_SMS_KEY = "PATIENT_ANCVISIT_DUE_SMS_KEY";
    public static final String PATIENT_TT_DUE_SMS_KEY = "PATIENT_TT_DUE_SMS_KEY";
    public static final String PATIENT_IPT_DUE_SMS_KEY = "PATIENT_IPT_DUE_SMS_KEY";
    public static final String PATIENT_PNC_MOTHER_DUE_SMS_KEY = "PATIENT_PNCMOTHER_DUE_SMS_KEY";
    public static final String PATIENT_PNC_BABY_DUE_SMS_KEY = "PATIENT_PNCBABY_DUE_SMS_KEY";
    public static final String PATIENT_BCG_DUE_SMS_KEY = "PATIENT_BCG_DUE_SMS_KEY";
    public static final String PATIENT_PENTA_DUE_SMS_KEY = "PATIENT_PENTA_DUE_SMS_KEY";
    public static final String PATIENT_YELLOW_FEVER_DUE_SMS_KEY = "PATIENT_YELLOWFEVER_DUE_SMS_KEY";
    public static final String PATIENT_MEASLES_DUE_SMS_KEY = "PATIENT_MEASLES_DUE_SMS_KEY";
    public static final String PATIENT_OPV_DUE_SMS_KEY = "PATIENT_OPV_DUE_SMS_KEY";
    public static final String PATIENT_IPTI_DUE_SMS_KEY = "PATIENT_IPTI_DUE_SMS_KEY";
    public static final String PATIENT_ANC_VISIT_LATE_SMS_KEY = "PATIENT_ANCVISIT_LATE_SMS_KEY";
    public static final String PATIENT_TT_LATE_SMS_KEY = "PATIENT_TT_LATE_SMS_KEY";
    public static final String PATIENT_IPT_LATE_SMS_KEY = "PATIENT_IPT_LATE_SMS_KEY";
    public static final String PATIENT_PNC_MOTHER_LATE_SMS_KEY = "PATIENT_PNCMOTHER_LATE_SMS_KEY";
    public static final String PATIENT_PNC_BABY_LATE_SMS_KEY = "PATIENT_PNCBABY_LATE_SMS_KEY";
    public static final String PATIENT_BCG_LATE_SMS_KEY = "PATIENT_BCG_LATE_SMS_KEY";
    public static final String PATIENT_PENTA_LATE_SMS_KEY = "PATIENT_PENTA_LATE_SMS_KEY";
    public static final String PATIENT_YELLOW_FEVER_LATE_SMS_KEY = "PATIENT_YELLOWFEVER_LATE_SMS_KEY";
    public static final String PATIENT_MEASLES_LATE_SMS_KEY = "PATIENT_MEASLES_LATE_SMS_KEY";
    public static final String PATIENT_OPV_LATE_SMS_KEY = "PATIENT_OPV_LATE_SMS_KEY";
    public static final String PATIENT_IPTI_LATE_SMS_KEY = "PATIENT_IPTI_LATE_SMS_KEY";
}
